setwd("~/Magic Briefcase/coursera/Exploratory/proj1")
dat <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880, sep = ";", col.names = colnames(read.table("household_power_consumption.txt", nrow = 1, header = TRUE, sep=";")))
dat$Date <- as.character(dat$Date)
dat$Time <- as.character(dat$Time)
dat$dateTime <- as.POSIXct(strptime(paste(dat$Date,dat$Time), "%d/%m/%Y %H:%M:%S"))
png(filename="plot4.png", width=480, height=480)
par(mfrow = c(2, 2), cex=0.65)
plot(dat$dateTime, dat$Global_active_power, xlab = "", ylab="Global Active Power", type="l")
plot(dat$dateTime, dat$Voltage, type="l", xlab="datetime", ylab="Voltage")
with(dat, {
        plot(dat$dateTime, dat$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab="")
        points(dat$dateTime, dat$Sub_metering_2, type="l", col = "red", ylab="Energy sub metering", xlab="")
        points(dat$dateTime, dat$Sub_metering_3, type="l", col = "blue", ylab="Energy sub metering", xlab="")
        legend("topright", lty=1, col = c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
})
plot(dat$dateTime, dat$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
