setwd("~/Magic Briefcase/coursera/Exploratory/proj1")
dat <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880, sep = ";", col.names = colnames(read.table("household_power_consumption.txt", nrow = 1, header = TRUE, sep=";")))
dat$Date <- as.character(dat$Date)
dat$Time <- as.character(dat$Time)
dat$dateTime <- as.POSIXct(strptime(paste(dat$Date,dat$Time), "%d/%m/%Y %H:%M:%S"))
hist(dat$Global_active_power, col = "red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png")
dev.off()