setwd("~/Magic Briefcase/coursera/Exploratory/proj1")
dat <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880, sep = ";", col.names = colnames(read.table("household_power_consumption.txt", nrow = 1, header = TRUE, sep=";")))
dat$Date <- as.character(dat$Date)
dat$Time <- as.character(dat$Time)
dat$dateTime <- as.POSIXct(strptime(paste(dat$Date,dat$Time), "%d/%m/%Y %H:%M:%S"))
with(dat, plot(dat$dateTime, dat$Sub_metering_1, type = "l", ylab="Energy sub metering", xlab=""))
with(dat, points(dat$dateTime, dat$Sub_metering_2, type="l", col = "red"))
with(dat, points(dat$dateTime, dat$Sub_metering_3, type="l", col = "blue"))
legend("topright", lty=1, col = c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()